version: '3.8'

services:
  strapi:
    image: 360xperts
    container_name: strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: postgres
      DATABASE_HOST: 192.168.4.167
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    volumes:
      - ./strapi-app:/srv/app
    ports:
      - "1337:1337"
    depends_on:
      - db
    networks:
      - strapi1-network

  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - strapi1-network

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - strapi1-network

networks:
  strapi1-network:
    driver: bridge

volumes:
  postgres-data:
